version: '3.5'

services:
  zookeeper:
    image: zookeeper:3.8
    container_name: zookeeper
    hostname: zookeeper

  clickhouse-node1:
    image: clickhouse/clickhouse-server:24
    container_name: clickhouse-node1
    hostname: clickhouse-node1
    environment:
      - CLICKHOUSE_ALWAYS_RUN_INITDB_SCRIPTS=true
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./data_ch/node1:/etc/clickhouse-server
      - ./data_ch/node1:/docker-entrypoint-initdb.d
    depends_on:
      - zookeeper

  clickhouse-node2:
    image: clickhouse/clickhouse-server:24
    container_name: clickhouse-node2
    hostname: clickhouse-node2
    environment:
      - CLICKHOUSE_ALWAYS_RUN_INITDB_SCRIPTS=true
    ports:
      - "8124:8123"
      - "9001:9000"
    volumes:
      - ./data_ch/node2:/etc/clickhouse-server
      - ./data_ch/node2:/docker-entrypoint-initdb.d
    depends_on:
      - zookeeper

  clickhouse-node3:
    image: clickhouse/clickhouse-server:24
    container_name: clickhouse-node3
    hostname: clickhouse-node3
    environment:
      - CLICKHOUSE_ALWAYS_RUN_INITDB_SCRIPTS=true
    ports:
      - "8125:8123"
      - "9002:9000"
    volumes:
      - ./data_ch/node3:/etc/clickhouse-server
      - ./data_ch/node3:/docker-entrypoint-initdb.d
    depends_on:
      - zookeeper

  clickhouse-node4:
    image: clickhouse/clickhouse-server:24
    container_name: clickhouse-node4
    hostname: clickhouse-node4
    environment:
      - CLICKHOUSE_ALWAYS_RUN_INITDB_SCRIPTS=true
    ports:
      - "8126:8123"
      - "9003:9000"
    volumes:
      - ./data_ch/node4:/etc/clickhouse-server
      - ./data_ch/node4:/docker-entrypoint-initdb.d
    depends_on:
      - zookeeper

  etl:
    image: etl
    build: ./etl
    container_name: etl
    depends_on:
      - zookeeper
      - clickhouse-node1
      - clickhouse-node2
      - clickhouse-node3
      - clickhouse-node4
    env_file:
      - ./etl/.env
