version: '3.5'

services:
  web:
      build: ./flask_app
      env_file:
        - ./flask_app/.env.container
      depends_on:
        - kafka-0

  kafka-0:
    image: bitnami/kafka:3.4
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-0:9092,EXTERNAL://127.0.0.1:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    volumes:
      - kafka_0_data-dev:/bitnami/kafka

  ui:
    image: provectuslabs/kafka-ui:v0.7.0
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka-0:9092
      - KAFKA_CLUSTERS_0_NAME=kraft

  zookeeper:
    image: zookeeper:3.8
    container_name: zookeeper
    hostname: zookeeper

  clickhouse-node1:
    image: clickhouse/clickhouse-server:24
    container_name: clickhouse-node1
    hostname: clickhouse-node1
    environment:
      - CLICKHOUSE_ALWAYS_RUN_INITDB_SCRIPTS=true
    volumes:
      - ./data_ch/node1:/etc/clickhouse-server
      - ./data_ch/node1:/docker-entrypoint-initdb.d
    depends_on:
      - zookeeper

  clickhouse-node2:
    image: clickhouse/clickhouse-server:24
    container_name: clickhouse-node2
    hostname: clickhouse-node2
    environment:
      - CLICKHOUSE_ALWAYS_RUN_INITDB_SCRIPTS=true
    volumes:
      - ./data_ch/node2:/etc/clickhouse-server
      - ./data_ch/node2:/docker-entrypoint-initdb.d
    depends_on:
      - zookeeper

  clickhouse-node3:
    image: clickhouse/clickhouse-server:24
    container_name: clickhouse-node3
    hostname: clickhouse-node3
    environment:
      - CLICKHOUSE_ALWAYS_RUN_INITDB_SCRIPTS=true
    volumes:
      - ./data_ch/node3:/etc/clickhouse-server
      - ./data_ch/node3:/docker-entrypoint-initdb.d
    depends_on:
      - zookeeper

  clickhouse-node4:
    image: clickhouse/clickhouse-server:24
    container_name: clickhouse-node4
    hostname: clickhouse-node4
    environment:
      - CLICKHOUSE_ALWAYS_RUN_INITDB_SCRIPTS=true
    volumes:
      - ./data_ch/node4:/etc/clickhouse-server
      - ./data_ch/node4:/docker-entrypoint-initdb.d
    depends_on:
      - zookeeper

  etl:
    image: etl
    build: ./etl
    container_name: etl
    depends_on:
      - zookeeper
      - clickhouse-node1
      - clickhouse-node2
      - clickhouse-node3
      - clickhouse-node4
      - kafka-0
    env_file:
      - ./etl/.env.container

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web


volumes:
  kafka_0_data-dev:
